# vi:set ft=dockerfile:
FROM registry.access.redhat.com/ubi8/python-39:latest

USER root

WORKDIR /managedtenant-cli

COPY . ./

RUN pip install pipenv

RUN pipenv lock --pre --clear

RUN pipenv install --dev

ENTRYPOINT ["make"]

CMD ["check", "test"]
